spring:
  application:
    name: Sandbox
  datasource:
    url: jdbc:mysql://${DB_URI:localhost:3306}
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
server:
  port: 80